apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-catalog-calls
  namespace: default
spec:
  selector:
    matchLabels:
      app: products-service
  rules:
  - from:
    - source:
        principals:
          - "spiffe://cluster.local/ns/default/sa/frontend-sa"
    to:
    - operation:
        methods: ["GET", "POST"]
        ports: ["8002"]
